[project]
name = "chess-engine-2"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.8.0",
]

# Expose a simple test runner so `uv run test` works.
[project.scripts]
test = "pytest:console_main"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"
